ARG VERSION
FROM almalinux:${VERSION:-9}

ARG Course="docker" \
    Trainer="sivakumar" \
    Author="info@joindevops.com" \
    Duration="120"

RUN echo "Course: ${Course}, Trainer: ${Trainer}, Author: ${Trainer} Duration: ${Duration} VERSION: ${VERSION}"    
CMD ["sleep", "1000"]